### ISSUE TITLE
Doesn't compile with nix 2.6 (nixos-unstable)

### ISSUE THREAD

**Issue by singron** [shlevy/nix-plugins#10]
```
[ 50%] Building CXX object CMakeFiles/nix-extra-builtins.dir/extra-builtins.cc.o
/build/source/extra-builtins.cc: In function 'void extraBuiltins(nix::EvalState&, const nix::Pos&, nix::Value**, nix::Value&)':
/build/source/extra-builtins.cc:45:19: error: 'class nix::EvalState' has no member named 'mkAttrs'
   45 |             state.mkAttrs(*arg, 2);
      |                   ^~~~~~~
/build/source/extra-builtins.cc:57:9: error: 'mkApp' was not declared in this scope
   57 |         mkApp(v, *fun, *arg);
      |         ^~~~~
/build/source/extra-builtins.cc:62:9: error: 'mkNull' was not declared in this scope
   62 |         mkNull(v);
      |         ^~~~~~
/build/source/extra-builtins.cc: In function 'void cflags(nix::EvalState&, const nix::Pos&, nix::Value**, nix::Value&)':
/build/source/extra-builtins.cc:72:11: error: 'class nix::EvalState' has no member named 'mkAttrs'
   72 |     state.mkAttrs(v, 3);
      |           ^~~~~~~
make[2]: *** [CMakeFiles/nix-extra-builtins.dir/build.make:76: CMakeFiles/nix-extra-builtins.dir/extra-builtins.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/nix-extra-builtins.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

E.g. https://hydra.nixos.org/build/166328127

EvalState::mkAttr was removed in https://github.com/NixOS/nix/commit/2b4c94482364c236b03f7f8b61aca7076ab4079d

I think the mkApp and mkNull functions were removed in https://github.com/NixOS/nix/commit/263a8d293c67488065296737cdadee3d0e122bf5

Both removals were part of https://github.com/NixOS/nix/pull/5864

**Comment by shlevy** [comment]
Thanks, will take a look
